-- ============================================================
-- 008 · MARKETS (country registry)
-- Every ISO 3166-1 country/territory, grouped by region, each with an
-- independent active/inactive toggle and payment-provider connection
-- status. This is the control surface for "which markets are open" —
-- launch is Azerbaijan only (pre-seeded active + connected to Epoint);
-- every other market ships closed until a human flips it on from the
-- admin panel, after the payment/legal/ops work for that country is
-- actually done. Nothing here auto-opens a market.
--
-- Region grouping is UN-style continents, with a few subregions split
-- out where they matter for a corridor-based rollout (Caucasus,
-- Central Asia, Middle East carved out of the Asia bucket) — those are
-- the neighboring markets most likely to be next after Azerbaijan.
-- ============================================================

create type market_payment_status_t as enum ('not_connected', 'pending', 'connected', 'suspended');

create table public.countries (
  iso2             char(2) primary key,
  iso3             char(3) not null,
  name             text not null,
  region           text not null,          -- continent-level grouping
  subregion        text not null,          -- finer grouping (defaults to region)
  currency_code    char(3),                -- nullable — fill in when a market is actually being worked on
  is_active        boolean not null default false,   -- market open for real users
  payment_provider text,                    -- e.g. 'epoint'; null until one is wired
  payment_status   market_payment_status_t not null default 'not_connected',
  notes            text,
  updated_at       timestamptz not null default now(),
  updated_by       uuid references public.users(id)
);

create index countries_region_idx on public.countries(region, subregion);
create index countries_active_idx on public.countries(is_active) where is_active;

create or replace function public.trg_countries_touch()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;

create trigger countries_touch
  before update on public.countries
  for each row execute function public.trg_countries_touch();

-- Client-readable (mobile app can show "SameWay is live in..." /
-- "coming soon to your country" copy); writes are admin-panel/service
-- role only.
alter table public.countries enable row level security;
create policy countries_read on public.countries for select using (true);

insert into public.countries
  (iso2, iso3, name, region, subregion, currency_code, is_active, payment_provider, payment_status)
values
  ('DZ', 'DZA', 'Algeria', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('AO', 'AGO', 'Angola', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('BJ', 'BEN', 'Benin', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('BW', 'BWA', 'Botswana', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('BF', 'BFA', 'Burkina Faso', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('BI', 'BDI', 'Burundi', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('CV', 'CPV', 'Cabo Verde', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('CM', 'CMR', 'Cameroon', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('CF', 'CAF', 'Central African Republic', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('TD', 'TCD', 'Chad', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('KM', 'COM', 'Comoros', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('CG', 'COG', 'Congo', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('CD', 'COD', 'Congo, The Democratic Republic of the', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('CI', 'CIV', 'Côte d''Ivoire', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('DJ', 'DJI', 'Djibouti', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('EG', 'EGY', 'Egypt', 'Africa', 'Africa', 'EGP', false, null, 'not_connected'),
  ('GQ', 'GNQ', 'Equatorial Guinea', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('ER', 'ERI', 'Eritrea', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('SZ', 'SWZ', 'Eswatini', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('ET', 'ETH', 'Ethiopia', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('TF', 'ATF', 'French Southern Territories', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('GA', 'GAB', 'Gabon', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('GM', 'GMB', 'Gambia', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('GH', 'GHA', 'Ghana', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('GN', 'GIN', 'Guinea', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('GW', 'GNB', 'Guinea-Bissau', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('KE', 'KEN', 'Kenya', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('LS', 'LSO', 'Lesotho', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('LR', 'LBR', 'Liberia', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('LY', 'LBY', 'Libya', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('MG', 'MDG', 'Madagascar', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('MW', 'MWI', 'Malawi', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('ML', 'MLI', 'Mali', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('MR', 'MRT', 'Mauritania', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('MU', 'MUS', 'Mauritius', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('YT', 'MYT', 'Mayotte', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('MA', 'MAR', 'Morocco', 'Africa', 'Africa', 'MAD', false, null, 'not_connected'),
  ('MZ', 'MOZ', 'Mozambique', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('NA', 'NAM', 'Namibia', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('NE', 'NER', 'Niger', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('NG', 'NGA', 'Nigeria', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('RW', 'RWA', 'Rwanda', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('RE', 'REU', 'Réunion', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('ST', 'STP', 'Sao Tome and Principe', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('SN', 'SEN', 'Senegal', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('SC', 'SYC', 'Seychelles', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('SL', 'SLE', 'Sierra Leone', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('SO', 'SOM', 'Somalia', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('ZA', 'ZAF', 'South Africa', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('SS', 'SSD', 'South Sudan', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('SD', 'SDN', 'Sudan', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('TZ', 'TZA', 'Tanzania, United Republic of', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('TG', 'TGO', 'Togo', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('TN', 'TUN', 'Tunisia', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('UG', 'UGA', 'Uganda', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('EH', 'ESH', 'Western Sahara', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('ZM', 'ZMB', 'Zambia', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('ZW', 'ZWE', 'Zimbabwe', 'Africa', 'Africa', null, false, null, 'not_connected'),
  ('AQ', 'ATA', 'Antarctica', 'Antarctica', 'Antarctica', null, false, null, 'not_connected'),
  ('BV', 'BVT', 'Bouvet Island', 'Antarctica', 'Antarctica', null, false, null, 'not_connected'),
  ('HM', 'HMD', 'Heard Island and McDonald Islands', 'Antarctica', 'Antarctica', null, false, null, 'not_connected'),
  ('AF', 'AFG', 'Afghanistan', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('BD', 'BGD', 'Bangladesh', 'Asia', 'Asia', 'BDT', false, null, 'not_connected'),
  ('BT', 'BTN', 'Bhutan', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('IO', 'IOT', 'British Indian Ocean Territory', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('BN', 'BRN', 'Brunei Darussalam', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('KH', 'KHM', 'Cambodia', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('CN', 'CHN', 'China', 'Asia', 'Asia', 'CNY', false, null, 'not_connected'),
  ('CX', 'CXR', 'Christmas Island', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('CC', 'CCK', 'Cocos (Keeling) Islands', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('CY', 'CYP', 'Cyprus', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('HK', 'HKG', 'Hong Kong', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('IN', 'IND', 'India', 'Asia', 'Asia', 'INR', false, null, 'not_connected'),
  ('ID', 'IDN', 'Indonesia', 'Asia', 'Asia', 'IDR', false, null, 'not_connected'),
  ('JP', 'JPN', 'Japan', 'Asia', 'Asia', 'JPY', false, null, 'not_connected'),
  ('KP', 'PRK', 'Korea, Democratic People''s Republic of', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('KR', 'KOR', 'Korea, Republic of', 'Asia', 'Asia', 'KRW', false, null, 'not_connected'),
  ('LA', 'LAO', 'Lao People''s Democratic Republic', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('MO', 'MAC', 'Macao', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('MY', 'MYS', 'Malaysia', 'Asia', 'Asia', 'MYR', false, null, 'not_connected'),
  ('MV', 'MDV', 'Maldives', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('MN', 'MNG', 'Mongolia', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('MM', 'MMR', 'Myanmar', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('NP', 'NPL', 'Nepal', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('PK', 'PAK', 'Pakistan', 'Asia', 'Asia', 'PKR', false, null, 'not_connected'),
  ('PH', 'PHL', 'Philippines', 'Asia', 'Asia', 'PHP', false, null, 'not_connected'),
  ('SG', 'SGP', 'Singapore', 'Asia', 'Asia', 'SGD', false, null, 'not_connected'),
  ('LK', 'LKA', 'Sri Lanka', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('TW', 'TWN', 'Taiwan, Province of China', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('TH', 'THA', 'Thailand', 'Asia', 'Asia', 'THB', false, null, 'not_connected'),
  ('TL', 'TLS', 'Timor-Leste', 'Asia', 'Asia', null, false, null, 'not_connected'),
  ('VN', 'VNM', 'Viet Nam', 'Asia', 'Asia', 'VND', false, null, 'not_connected'),
  ('AM', 'ARM', 'Armenia', 'Asia', 'Caucasus', 'AMD', false, null, 'not_connected'),
  ('AZ', 'AZE', 'Azerbaijan', 'Asia', 'Caucasus', 'AZN', true, 'epoint', 'connected'),
  ('GE', 'GEO', 'Georgia', 'Asia', 'Caucasus', 'GEL', false, null, 'not_connected'),
  ('KZ', 'KAZ', 'Kazakhstan', 'Asia', 'Central Asia', 'KZT', false, null, 'not_connected'),
  ('KG', 'KGZ', 'Kyrgyzstan', 'Asia', 'Central Asia', null, false, null, 'not_connected'),
  ('TJ', 'TJK', 'Tajikistan', 'Asia', 'Central Asia', null, false, null, 'not_connected'),
  ('TM', 'TKM', 'Turkmenistan', 'Asia', 'Central Asia', null, false, null, 'not_connected'),
  ('UZ', 'UZB', 'Uzbekistan', 'Asia', 'Central Asia', 'UZS', false, null, 'not_connected'),
  ('BH', 'BHR', 'Bahrain', 'Asia', 'Middle East', 'BHD', false, null, 'not_connected'),
  ('IR', 'IRN', 'Iran, Islamic Republic of', 'Asia', 'Middle East', null, false, null, 'not_connected'),
  ('IQ', 'IRQ', 'Iraq', 'Asia', 'Middle East', null, false, null, 'not_connected'),
  ('IL', 'ISR', 'Israel', 'Asia', 'Middle East', 'ILS', false, null, 'not_connected'),
  ('JO', 'JOR', 'Jordan', 'Asia', 'Middle East', 'JOD', false, null, 'not_connected'),
  ('KW', 'KWT', 'Kuwait', 'Asia', 'Middle East', 'KWD', false, null, 'not_connected'),
  ('LB', 'LBN', 'Lebanon', 'Asia', 'Middle East', null, false, null, 'not_connected'),
  ('OM', 'OMN', 'Oman', 'Asia', 'Middle East', 'OMR', false, null, 'not_connected'),
  ('PS', 'PSE', 'Palestine, State of', 'Asia', 'Middle East', null, false, null, 'not_connected'),
  ('QA', 'QAT', 'Qatar', 'Asia', 'Middle East', 'QAR', false, null, 'not_connected'),
  ('SA', 'SAU', 'Saudi Arabia', 'Asia', 'Middle East', 'SAR', false, null, 'not_connected'),
  ('SY', 'SYR', 'Syrian Arab Republic', 'Asia', 'Middle East', null, false, null, 'not_connected'),
  ('TR', 'TUR', 'Türkiye', 'Asia', 'Middle East', 'TRY', false, null, 'not_connected'),
  ('AE', 'ARE', 'United Arab Emirates', 'Asia', 'Middle East', 'AED', false, null, 'not_connected'),
  ('YE', 'YEM', 'Yemen', 'Asia', 'Middle East', null, false, null, 'not_connected'),
  ('AL', 'ALB', 'Albania', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('AD', 'AND', 'Andorra', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('AT', 'AUT', 'Austria', 'Europe', 'Europe', 'EUR', false, null, 'not_connected'),
  ('BY', 'BLR', 'Belarus', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('BE', 'BEL', 'Belgium', 'Europe', 'Europe', 'EUR', false, null, 'not_connected'),
  ('BA', 'BIH', 'Bosnia and Herzegovina', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('BG', 'BGR', 'Bulgaria', 'Europe', 'Europe', 'BGN', false, null, 'not_connected'),
  ('HR', 'HRV', 'Croatia', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('CZ', 'CZE', 'Czechia', 'Europe', 'Europe', 'CZK', false, null, 'not_connected'),
  ('DK', 'DNK', 'Denmark', 'Europe', 'Europe', 'DKK', false, null, 'not_connected'),
  ('EE', 'EST', 'Estonia', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('FO', 'FRO', 'Faroe Islands', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('FI', 'FIN', 'Finland', 'Europe', 'Europe', 'EUR', false, null, 'not_connected'),
  ('FR', 'FRA', 'France', 'Europe', 'Europe', 'EUR', false, null, 'not_connected'),
  ('DE', 'DEU', 'Germany', 'Europe', 'Europe', 'EUR', false, null, 'not_connected'),
  ('GI', 'GIB', 'Gibraltar', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('GR', 'GRC', 'Greece', 'Europe', 'Europe', 'EUR', false, null, 'not_connected'),
  ('GG', 'GGY', 'Guernsey', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('VA', 'VAT', 'Holy See (Vatican City State)', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('HU', 'HUN', 'Hungary', 'Europe', 'Europe', 'HUF', false, null, 'not_connected'),
  ('IS', 'ISL', 'Iceland', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('IE', 'IRL', 'Ireland', 'Europe', 'Europe', 'EUR', false, null, 'not_connected'),
  ('IM', 'IMN', 'Isle of Man', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('IT', 'ITA', 'Italy', 'Europe', 'Europe', 'EUR', false, null, 'not_connected'),
  ('JE', 'JEY', 'Jersey', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('LV', 'LVA', 'Latvia', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('LI', 'LIE', 'Liechtenstein', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('LT', 'LTU', 'Lithuania', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('LU', 'LUX', 'Luxembourg', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('MT', 'MLT', 'Malta', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('MD', 'MDA', 'Moldova, Republic of', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('MC', 'MCO', 'Monaco', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('ME', 'MNE', 'Montenegro', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('NL', 'NLD', 'Netherlands', 'Europe', 'Europe', 'EUR', false, null, 'not_connected'),
  ('MK', 'MKD', 'North Macedonia', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('NO', 'NOR', 'Norway', 'Europe', 'Europe', 'NOK', false, null, 'not_connected'),
  ('PL', 'POL', 'Poland', 'Europe', 'Europe', 'PLN', false, null, 'not_connected'),
  ('PT', 'PRT', 'Portugal', 'Europe', 'Europe', 'EUR', false, null, 'not_connected'),
  ('RO', 'ROU', 'Romania', 'Europe', 'Europe', 'RON', false, null, 'not_connected'),
  ('RU', 'RUS', 'Russian Federation', 'Europe', 'Europe', 'RUB', false, null, 'not_connected'),
  ('SM', 'SMR', 'San Marino', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('RS', 'SRB', 'Serbia', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('SK', 'SVK', 'Slovakia', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('SI', 'SVN', 'Slovenia', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('ES', 'ESP', 'Spain', 'Europe', 'Europe', 'EUR', false, null, 'not_connected'),
  ('SJ', 'SJM', 'Svalbard and Jan Mayen', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('SE', 'SWE', 'Sweden', 'Europe', 'Europe', 'SEK', false, null, 'not_connected'),
  ('CH', 'CHE', 'Switzerland', 'Europe', 'Europe', 'CHF', false, null, 'not_connected'),
  ('UA', 'UKR', 'Ukraine', 'Europe', 'Europe', 'UAH', false, null, 'not_connected'),
  ('GB', 'GBR', 'United Kingdom', 'Europe', 'Europe', 'GBP', false, null, 'not_connected'),
  ('AX', 'ALA', 'Åland Islands', 'Europe', 'Europe', null, false, null, 'not_connected'),
  ('AI', 'AIA', 'Anguilla', 'North America', 'North America', null, false, null, 'not_connected'),
  ('AG', 'ATG', 'Antigua and Barbuda', 'North America', 'North America', null, false, null, 'not_connected'),
  ('AW', 'ABW', 'Aruba', 'North America', 'North America', null, false, null, 'not_connected'),
  ('BS', 'BHS', 'Bahamas', 'North America', 'North America', null, false, null, 'not_connected'),
  ('BB', 'BRB', 'Barbados', 'North America', 'North America', null, false, null, 'not_connected'),
  ('BZ', 'BLZ', 'Belize', 'North America', 'North America', null, false, null, 'not_connected'),
  ('BM', 'BMU', 'Bermuda', 'North America', 'North America', null, false, null, 'not_connected'),
  ('BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'North America', 'North America', null, false, null, 'not_connected'),
  ('CA', 'CAN', 'Canada', 'North America', 'North America', 'CAD', false, null, 'not_connected'),
  ('KY', 'CYM', 'Cayman Islands', 'North America', 'North America', null, false, null, 'not_connected'),
  ('CR', 'CRI', 'Costa Rica', 'North America', 'North America', null, false, null, 'not_connected'),
  ('CU', 'CUB', 'Cuba', 'North America', 'North America', null, false, null, 'not_connected'),
  ('CW', 'CUW', 'Curaçao', 'North America', 'North America', null, false, null, 'not_connected'),
  ('DM', 'DMA', 'Dominica', 'North America', 'North America', null, false, null, 'not_connected'),
  ('DO', 'DOM', 'Dominican Republic', 'North America', 'North America', null, false, null, 'not_connected'),
  ('SV', 'SLV', 'El Salvador', 'North America', 'North America', null, false, null, 'not_connected'),
  ('GL', 'GRL', 'Greenland', 'North America', 'North America', null, false, null, 'not_connected'),
  ('GD', 'GRD', 'Grenada', 'North America', 'North America', null, false, null, 'not_connected'),
  ('GP', 'GLP', 'Guadeloupe', 'North America', 'North America', null, false, null, 'not_connected'),
  ('GT', 'GTM', 'Guatemala', 'North America', 'North America', null, false, null, 'not_connected'),
  ('HT', 'HTI', 'Haiti', 'North America', 'North America', null, false, null, 'not_connected'),
  ('HN', 'HND', 'Honduras', 'North America', 'North America', null, false, null, 'not_connected'),
  ('JM', 'JAM', 'Jamaica', 'North America', 'North America', null, false, null, 'not_connected'),
  ('MQ', 'MTQ', 'Martinique', 'North America', 'North America', null, false, null, 'not_connected'),
  ('MX', 'MEX', 'Mexico', 'North America', 'North America', 'MXN', false, null, 'not_connected'),
  ('MS', 'MSR', 'Montserrat', 'North America', 'North America', null, false, null, 'not_connected'),
  ('NI', 'NIC', 'Nicaragua', 'North America', 'North America', null, false, null, 'not_connected'),
  ('PA', 'PAN', 'Panama', 'North America', 'North America', null, false, null, 'not_connected'),
  ('PR', 'PRI', 'Puerto Rico', 'North America', 'North America', null, false, null, 'not_connected'),
  ('BL', 'BLM', 'Saint Barthélemy', 'North America', 'North America', null, false, null, 'not_connected'),
  ('KN', 'KNA', 'Saint Kitts and Nevis', 'North America', 'North America', null, false, null, 'not_connected'),
  ('LC', 'LCA', 'Saint Lucia', 'North America', 'North America', null, false, null, 'not_connected'),
  ('MF', 'MAF', 'Saint Martin (French part)', 'North America', 'North America', null, false, null, 'not_connected'),
  ('PM', 'SPM', 'Saint Pierre and Miquelon', 'North America', 'North America', null, false, null, 'not_connected'),
  ('VC', 'VCT', 'Saint Vincent and the Grenadines', 'North America', 'North America', null, false, null, 'not_connected'),
  ('SX', 'SXM', 'Sint Maarten (Dutch part)', 'North America', 'North America', null, false, null, 'not_connected'),
  ('TT', 'TTO', 'Trinidad and Tobago', 'North America', 'North America', null, false, null, 'not_connected'),
  ('TC', 'TCA', 'Turks and Caicos Islands', 'North America', 'North America', null, false, null, 'not_connected'),
  ('US', 'USA', 'United States', 'North America', 'North America', 'USD', false, null, 'not_connected'),
  ('VG', 'VGB', 'Virgin Islands, British', 'North America', 'North America', null, false, null, 'not_connected'),
  ('VI', 'VIR', 'Virgin Islands, U.S.', 'North America', 'North America', null, false, null, 'not_connected'),
  ('AS', 'ASM', 'American Samoa', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('AU', 'AUS', 'Australia', 'Oceania', 'Oceania', 'AUD', false, null, 'not_connected'),
  ('CK', 'COK', 'Cook Islands', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('FJ', 'FJI', 'Fiji', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('PF', 'PYF', 'French Polynesia', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('GU', 'GUM', 'Guam', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('KI', 'KIR', 'Kiribati', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('MH', 'MHL', 'Marshall Islands', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('FM', 'FSM', 'Micronesia, Federated States of', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('NR', 'NRU', 'Nauru', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('NC', 'NCL', 'New Caledonia', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('NZ', 'NZL', 'New Zealand', 'Oceania', 'Oceania', 'NZD', false, null, 'not_connected'),
  ('NU', 'NIU', 'Niue', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('NF', 'NFK', 'Norfolk Island', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('MP', 'MNP', 'Northern Mariana Islands', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('PW', 'PLW', 'Palau', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('PG', 'PNG', 'Papua New Guinea', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('PN', 'PCN', 'Pitcairn', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('WS', 'WSM', 'Samoa', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('SB', 'SLB', 'Solomon Islands', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('TK', 'TKL', 'Tokelau', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('TO', 'TON', 'Tonga', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('TV', 'TUV', 'Tuvalu', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('UM', 'UMI', 'United States Minor Outlying Islands', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('VU', 'VUT', 'Vanuatu', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('WF', 'WLF', 'Wallis and Futuna', 'Oceania', 'Oceania', null, false, null, 'not_connected'),
  ('AR', 'ARG', 'Argentina', 'South America', 'South America', 'ARS', false, null, 'not_connected'),
  ('BO', 'BOL', 'Bolivia, Plurinational State of', 'South America', 'South America', null, false, null, 'not_connected'),
  ('BR', 'BRA', 'Brazil', 'South America', 'South America', 'BRL', false, null, 'not_connected'),
  ('CL', 'CHL', 'Chile', 'South America', 'South America', null, false, null, 'not_connected'),
  ('CO', 'COL', 'Colombia', 'South America', 'South America', null, false, null, 'not_connected'),
  ('EC', 'ECU', 'Ecuador', 'South America', 'South America', null, false, null, 'not_connected'),
  ('FK', 'FLK', 'Falkland Islands (Malvinas)', 'South America', 'South America', null, false, null, 'not_connected'),
  ('GF', 'GUF', 'French Guiana', 'South America', 'South America', null, false, null, 'not_connected'),
  ('GY', 'GUY', 'Guyana', 'South America', 'South America', null, false, null, 'not_connected'),
  ('PY', 'PRY', 'Paraguay', 'South America', 'South America', null, false, null, 'not_connected'),
  ('PE', 'PER', 'Peru', 'South America', 'South America', null, false, null, 'not_connected'),
  ('GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'South America', 'South America', null, false, null, 'not_connected'),
  ('SR', 'SUR', 'Suriname', 'South America', 'South America', null, false, null, 'not_connected'),
  ('UY', 'URY', 'Uruguay', 'South America', 'South America', null, false, null, 'not_connected'),
  ('VE', 'VEN', 'Venezuela, Bolivarian Republic of', 'South America', 'South America', null, false, null, 'not_connected')
on conflict (iso2) do nothing;
