-- ============================================================
-- 015 · RIDE INQUIRIES — pre-booking "Negocjuj" path (part 1 of 2)
--
-- Found by direct comparison against BlaBlaCar: before ever tapping
-- "Book," there's a separate "Negotiate" button that opens four
-- templated questions (different meeting point / different drop-off /
-- another special request / just want to chat), leading to a message
-- thread with the driver. This is NOT the same thing as our existing
-- "boost your chances" message (screen 45) — that one fires AFTER a
-- booking request already exists. This is earlier: no booking, no
-- request, just a question.
--
-- Checked before building: our conversations table already has
-- nullable booking_id (so a ride-only thread is structurally
-- possible), but nothing ever created one pre-booking — the only
-- insert path is trg_booking_conversation, gated on a booking reaching
-- 'confirmed'. That's a real, complete gap, not a partial one.
-- ============================================================

-- This file holds ONLY the enum addition; everything else lives in
-- 016_ride_inquiries_body.sql. Originally both were one file with the
-- ALTER TYPE as the first statement, but `supabase db push` wraps a
-- migration file in ONE transaction, and Postgres refuses to use a
-- newly added enum value anywhere in the transaction that added it
-- (SQLSTATE 55P04, "unsafe use of new value") — the partial index in
-- the body (`where type = 'inquiry'`) tripped exactly that. Separate
-- files run in separate transactions, which is the supported fix.
alter type public.conversation_type_t add value if not exists 'inquiry';
